
CREATE  DATABASE tripleBackendHomework;
USE tripleBackendHomework;   

CREATE TABLE TRIPLE_USER(
	USER_ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE TRIPLE_PLACE(
	PLACE_ID varchar(50) PRIMARY KEY
);
CREATE TABLE TRIPLE_REVIEW(
	REVIEW_ID VARCHAR(50) PRIMARY KEY,
	CONTENT VARCHAR(50),
	REVIEW_CREATEDTIME DATETIME DEFAULT(NOW()),
	REVIEW_UPDATEDTIME DATETIME DEFAULT(NOW()),
	USER_ID VARCHAR(50),
	PLACE_ID VARCHAR(50),
	constraint FK_TRIPLE_REVIEW_USER_ID foreign key (USER_ID) references TRIPLE_USER(USER_ID),
	constraint FK_TRIPLE_REVIEW_PLACE_ID foreign key (PLACE_ID) references TRIPLE_PLACE(PLACE_ID)
);

-- 주문번호

-- https://spiderwebcoding.tistory.com/6
CREATE TABLE TRIPLE_POINTHISTORY(
	POINTHISTORY_ID VARCHAR(50) PRIMARY KEY,
	POINTHISTORY_GRANTPOINT INT,
	REVIEW_ID VARCHAR(50),
	USER_ID VARCHAR(50),
	POINTHISTORY_CREATEDTIME DATETIME DEFAULT(NOW()),
	POINTHISTORY_REASON VARCHAR(50),
	key IDX_POINTHISTORY(USER_ID,REVIEW_ID)
);


CREATE TABLE TRIPLE_ATTACHEDPHOTO(
	ATTACHEDPHOTO_IDS VARCHAR(50) PRIMARY KEY ,
	REVIEW_ID VARCHAR(50),
	USER_ID VARCHAR(50),
	constraint FK_TRIPLE_ATTACHEDPHOTO_USER_ID foreign key (USER_ID) references TRIPLE_USER(USER_ID),
	constraint FK_TRIPLE_ATTACHEDPHOTO_REVIEW_ID foreign key (REVIEW_ID) references TRIPLE_REVIEW(REVIEW_ID)
);



